SELECT f.FLAVOR
FROM FIRST_HALF f 
INNER JOIN (SELECT FLAVOR,SUM(TOTAL_ORDER)AS JULY_TOTAL_ORDER
           FROM JULY 
           GROUP BY FLAVOR) y
            ON f.FLAVOR = y.FLAVOR
ORDER BY f.TOTAL_ORDER+ JULY_TOTAL_ORDER DESC 
LIMIT 3;
